# SpeedPlayer configuration
update-ticks: 2
show-on-join: true
max-display-speed: 10.0
ignore-vehicles: true
ignore-spectators: false

# BossBar colors:
# BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
normal-color: GREEN
fast-color: YELLOW
very-fast-color: RED

# Thresholds in blocks/second
fast-threshold: 6.0
very-fast-threshold: 10.0
